import torch
import pandas as pd
from typing import Tuple, List
from transformers import AutoTokenizer, AutoModelForCausalLM
from tqdm.auto import tqdm 
from collections import Counter

torch.manual_seed(42)
torch.cuda.manual_seed(42)




def interact(model: torch.nn.Module, tokenizer, usr_input: str, max_new_tokens: int = 256, sys_prompt = "") -> str:
  """
  Return the answer generated by the model to a user query
  """
  
  # Setup the prompt
  if sys_prompt:
    prompt =  f"{sys_prompt}{usr_input} [/INST]"
  else:
    prompt = f"[INST] {usr_input} [/INST]"

  # Pass the prompt and input to the tokenizer and sending to model's device
  inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

  # get generation results
  output = model.generate(**inputs, use_cache = True, max_new_tokens = max_new_tokens, temperature = 0.1)

  #tokenizer.decode(output[0], skip_prompt=True, skip_special_tokens=True)
  return tokenizer.batch_decode(output,skip_prompt=True, skip_special_tokens = True)[0].split("[/INST]")[-1].strip()


#get the results and the swapped results
def get_results(model,
                tokenizer,
                df:pd.DataFrame, 
                sys_prompt:str = "",
                task:str = "questions", save_df = False,
                out_path:str = "./results",
                data: str = "") -> Tuple[pd.DataFrame, pd.DataFrame]: #TODO fix the output path functionality

  """
  Feed inputs (qestions or statements) to the llm and get results answers. Test the correct answers on a swapped version.
  
  Return:
  DataFrame with nodes, total inputs and answers
  DataFrame with nodes, swapped inputs and relative answers. This is done on a subset of the first answers

  """

  #store the nodes
  nodes = df["nodes"].tolist()

  # format the prompt appropriately and extract te right input following the chosen task
  if task == "questions":
    sents = df["questions"].tolist()
    swapped = df["swapped_questions"].tolist()

    #if a prompt is not specified use this as default
    if not sys_prompt:
      sys_prompt = "[INST] <<SYS>>\n###Instruction###\nYour task is to answer the following question and you MUST answer strictly with 'yes' or 'no'.<</SYS>>\n\n###Question###\n"

  # if true or false task is chosen
  elif task == "statements":
    sents = df["statements"].tolist()
    swapped = df["swapped_statements"].tolist()

    #if a prompt is not specified use this as default
    if not sys_prompt:
      sys_prompt = "[INST] <<SYS>>\n###Instruction###\nYour task is to judge if the following statement is true or false. You MUST answer strictly with 'true' or 'false'.<</SYS>>\n\n###Statement###\n"

  else:
    print("Invalid task. Choose between 'questions' and 'statements'.")
    return

  print(f"\nStarting feeding the model with {task} inputs\n")
  print(f"Using the following prompt:\n\n {sys_prompt}")

  #feeding the model with the chosen inputs
  answers = [interact(model, tokenizer, s, max_new_tokens = 2, sys_prompt = sys_prompt) for s in tqdm(sents) if s]   

# test the swapped only on the positive answers!!
  print(f"\nStarting feeding the model with {task} swapped\n")
  # answer_swapped = [interact(s, max_new_tokens = 2, sys_prompt = SYS_PROMPT5) for s in tqdm(swapped) if s]
  #extract the correct answers to test them on the swapped version
  qas = list(zip(sents, answers))
  swapped2test = []
  nodes2swap = []
  for i in range(len(qas)):
    if qas[i][1].lower() in ["yes", "true"]:
      swapped2test.append(swapped[i])
      nodes2swap.append(nodes[i])

  # feed the swapped answers
  answer_swapped = [interact(model, tokenizer, s, max_new_tokens = 2, sys_prompt = sys_prompt) for s in tqdm(swapped2test) if s]

  # save the results in a dataframe
  results = pd.DataFrame(zip(nodes, sents, answers),
                         columns = ["nodes", "inputs", "answers"]).set_index("nodes")
  # save the swapped results in a dataframe
  results_swapped = pd.DataFrame(zip(nodes2swap, swapped2test, answer_swapped),
                                 columns = ["nodes", "swapped_inputs", "answers_swapped"]).set_index("nodes")
  
  #write the df results on disk //TODO set a default path for the results
  if save_df:
    results.to_csv(f"{out_path}/{data}_{task}_results.tsv", sep = "\t")
    results_swapped.to_csv(f"{out_path}/{data}_{task}_results_swap.tsv", sep = "\t")

    print(f"Results DataFrames saved at {out_path}")
  print(f"\nBrief summary for {task}: {Counter(answers)}")
  print(f"\nBrief summary for {task}_swapped: {Counter(answer_swapped)}")
        
        
  return results, results_swapped